### ISSUE TITLE
 WARN ajv-keywords@2.1.0 requires while installing backhand service

### ISSUE THREAD

**Issue by anarayn** [backand/angular2-sdk#3]
I am trying to install backhand service  for current ionic version during installation I get below warning.

└─┬ @backand/angular2-sdk@1.2.6 
  ├── @angular/core@2.4.10 
  ├── @backand/vanilla-sdk@1.2.7 
  └── zone.js@0.7.8 

npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.

**Comment by felansu** [comment]
Hi  friend, same issue !

**Comment by singhmohancs** [comment]
@anarayn @felansu Can you share following details?

- Node version?
- Ionic Cli version ?
- Which version of Ionic App are you building with v2 or v3?

I am not facing this issue. I am working with latest versions.

<img width="1020" alt="screen shot 2017-10-12 at 9 19 58 am" src="https://user-images.githubusercontent.com/283132/31478525-93690e10-af2e-11e7-88a4-4558984a118a.png">

**Comment by rannn505** [comment]
Hey @anarayn ,

The angular2-sdk's only dependencies are: 
"dependencies": {
    "@angular/core": "^2.4.6",
    "@backand/vanilla-sdk": "^1.2.12",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  }
and the @backand/vanilla-sdk has no dependencies at all....
so I believe that one of the three other dependencies raises the warning you specified.
I suggest that you update the dependencies on your project and also install the dependency that appears in the warning, just in case.

Please let me know if you need further assistance. 👍
